"""Automated Protocol Specification Documentation Generator for OmniUART."""

from __future__ import annotations

import html
from pathlib import Path
from typing import List, Optional, Union

from omniuart.core.catalog import CatalogManager
from omniuart.core.models import ProtocolSpec, load_protocol


def generate_markdown_docs(spec: ProtocolSpec) -> str:
    """Generate Markdown specification document for a protocol."""
    meta = spec.metadata
    lines: List[str] = []
    lines.append(f"# Hardware Protocol Specification: {meta.name}")
    lines.append("")
    lines.append(f"**Version**: `{meta.version}`  ")
    if meta.author:
        lines.append(f"**Author**: {meta.author}  ")
    lines.append(f"**Physical Layer**: `{spec.serial_config.baudrate} bps, {spec.serial_config.bytesize}N{spec.serial_config.stopbits}`  ")
    lines.append(f"**Framing**: `{spec.framing.type.value}`  ")
    if spec.framing.integrity:
        lines.append(f"**Integrity Algorithm**: `{spec.framing.integrity.algorithm}`  ")
    lines.append("")
    if meta.description:
        lines.append(f"## Description\n{meta.description}\n")

    lines.append("## Command Catalog & Message Signatures\n")

    # Group commands by tag
    tag_map = {}
    for cmd in spec.commands:
        tags = cmd.tags if cmd.tags else ["general"]
        for tag in tags:
            tag_map.setdefault(tag, []).append(cmd)

    for tag, cmds in tag_map.items():
        lines.append(f"### Category: {tag.upper()}\n")
        for cmd in cmds:
            desc = f" - {cmd.description}" if cmd.description else ""
            cmd_id_str = f"0x{cmd.id:02X}" if isinstance(cmd.id, int) else str(cmd.id)
            lines.append(f"#### `{cmd.name}` (Command ID: `{cmd_id_str}`){desc}\n")
            if cmd.parameters:
                lines.append("| Parameter | Type | Unit | Range / Constraints | Options |")
                lines.append("| :--- | :--- | :--- | :--- | :--- |")
                for p in cmd.parameters:
                    unit = p.unit or "-"
                    rng = f"[{p.min}, {p.max}]" if p.min is not None else "-"
                    opts = f"`{p.options}`" if p.options else "-"
                    lines.append(f"| `{p.name}` | `{p.type.value}` | {unit} | {rng} | {opts} |")
                lines.append("")
            if cmd.response:
                lines.append(f"**Expected Response Payload** (Timeout: `{cmd.response.timeout_ms} ms`):\n")
                lines.append("| Field Name | Type | Unit |")
                lines.append("| :--- | :--- | :--- |")
                for rf in cmd.response.fields:
                    rf_unit = rf.unit or "-"
                    lines.append(f"| `{rf.name}` | `{rf.type.value}` | {rf_unit} |")
                lines.append("")

    return "\n".join(lines)


def generate_html_docs(spec: ProtocolSpec) -> str:
    """Generate standalone HTML specification page for a protocol."""
    md_content = generate_markdown_docs(spec)
    title = html.escape(spec.metadata.name)
    
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{title} - OmniUART Protocol Specification</title>
  <style>
    body {{
      font-family: system-ui, -apple-system, sans-serif;
      line-height: 1.6;
      max-width: 900px;
      margin: 2rem auto;
      padding: 0 1rem;
      background: #0f172a;
      color: #f8fafc;
    }}
    h1, h2, h3, h4 {{ color: #38bdf8; border-bottom: 1px solid #334155; padding-bottom: 0.3rem; }}
    code {{ background: #1e293b; color: #34d399; padding: 0.2rem 0.4rem; border-radius: 4px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; background: #1e293b; }}
    th, td {{ padding: 0.75rem; border: 1px solid #334155; text-align: left; }}
    th {{ background: #334155; color: #38bdf8; }}
    .header-bar {{ background: #1e293b; padding: 1.5rem; border-radius: 8px; border: 1px solid #334155; }}
  </style>
</head>
<body>
  <div class="header-bar">
    <h1>⚡ {title} Specification</h1>
    <p>Auto-generated by OmniUART Protocol Documentation Engine</p>
  </div>
  <pre style="white-space: pre-wrap; word-break: break-word;">{html.escape(md_content)}</pre>
</body>
</html>"""


def build_site_documentation(output_dir: Union[str, Path]) -> Path:
    """Build static documentation site for all discovered protocols for GitHub Pages publishing."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    catalog = CatalogManager()
    summary = catalog.catalog_summary()

    index_lines = [
        "<!DOCTYPE html>",
        "<html lang='en'>",
        "<head>",
        "  <meta charset='UTF-8'>",
        "  <title>OmniUART Protocol Specification Hub</title>",
        "  <style>",
        "    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; background: #0f172a; color: #fff; padding: 0 1rem; }",
        "    h1 { color: #38bdf8; }",
        "    .card { background: #1e293b; padding: 1rem 1.5rem; margin: 1rem 0; border-radius: 8px; border: 1px solid #334155; }",
        "    a { color: #34d399; text-decoration: none; font-weight: bold; }",
        "  </style>",
        "</head>",
        "<body>",
        "  <h1>⚡ OmniUART Hardware Protocol Specification Hub</h1>",
        "  <p>Auto-generated protocol documentation and message signatures published via GitHub Pages pipeline.</p>",
    ]

    for p in summary["protocols"]:
        spec = catalog.get_protocol(p["filename"])
        if not spec:
            continue
        safe_stem = Path(p["filename"]).stem
        html_filename = f"{safe_stem}.html"
        md_filename = f"{safe_stem}.md"

        (out / html_filename).write_text(generate_html_docs(spec), encoding="utf-8")
        (out / md_filename).write_text(generate_markdown_docs(spec), encoding="utf-8")

        index_lines.append(
            f"  <div class='card'>"
            f"    <h3>{html.escape(spec.metadata.name)} (v{spec.metadata.version})</h3>"
            f"    <p>{html.escape(spec.metadata.description or '')}</p>"
            f"    <p>Baudrate: {spec.serial_config.baudrate} bps | Commands: {len(spec.commands)}</p>"
            f"    <p><a href='{html_filename}'>📄 View HTML Specs</a> | <a href='{md_filename}'>📝 View Markdown</a></p>"
            f"  </div>"
        )

    index_lines.extend(["</body>", "</html>"])
    (out / "index.html").write_text("\n".join(index_lines), encoding="utf-8")

    return out
