"""Artefact Generator Engine for OmniUART Protocols.

Generates Wireshark Lua dissectors, C headers, Python dataclasses, and JSON Schemas from ProtocolSpec definitions.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict
from omniuart.core.models import FieldType, ProtocolSpec


def _c_ident(name: str) -> str:
    """Sanitise string to valid C identifier."""
    clean = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if clean and clean[0].isdigit():
        clean = f"_{clean}"
    return clean


def _py_type(ft: FieldType) -> str:
    val = ft.value if hasattr(ft, "value") else str(ft)
    if val in ("float32", "float64", "float"):
        return "float"
    if val in ("bool", "boolean"):
        return "bool"
    if val in ("string", "str", "text", "ascii"):
        return "str"
    if val in ("bytes", "hex", "raw", "binary"):
        return "bytes"
    return "int"


def _c_type(ft: FieldType) -> str:
    val = ft.value if hasattr(ft, "value") else str(ft)
    mapping = {
        "uint8": "uint8_t",
        "int8": "int8_t",
        "uint16": "uint16_t",
        "int16": "int16_t",
        "uint32": "uint32_t",
        "int32": "int32_t",
        "uint64": "uint64_t",
        "int64": "int64_t",
        "float32": "float",
        "float64": "double",
        "bool": "uint8_t",
        "boolean": "uint8_t",
        "enum": "uint8_t",
    }
    return mapping.get(val, "uint8_t")


def generate_wireshark_dissector(spec: ProtocolSpec) -> str:
    """Generate a Wireshark Lua dissector for USER0 (encap 147) PCAPNG captures."""
    name_clean = _c_ident(spec.metadata.name)
    lines = [
        f"-- Wireshark Lua Dissector for {spec.metadata.name} (v{spec.metadata.version})",
        "-- Auto-generated by OmniUART",
        "",
        f'local p_{name_clean} = Proto("{name_clean}", "{spec.metadata.name} Protocol")',
        "",
        f"local f_cmd_id = ProtoField.uint8(\"{name_clean}.cmd_id\", \"Command ID\", base.HEX)",
        f"p_{name_clean}.fields = {{ f_cmd_id }}",
        "",
        f"function p_{name_clean}.dissector(buffer, pinfo, tree)",
        f'    pinfo.cols.protocol = "{spec.metadata.name}"',
        f'    local subtree = tree:add(p_{name_clean}, buffer(), "{spec.metadata.name} Frame")',
        "    if buffer:len() > 0 then",
        f"        subtree:add(f_cmd_id, buffer(0, 1))",
        "    end",
        "end",
        "",
        "-- Register dissector for USER0 PCAPNG linktype (147)",
        "local wtap_encap_table = DissectorTable.get(\"wtap_encap\")",
        "if wtap_encap_table then",
        f"    wtap_encap_table:add(147, p_{name_clean})",
        "end",
    ]
    return "\n".join(lines)


def generate_c_header(spec: ProtocolSpec) -> str:
    """Generate C header file with packed structs, opcode enums, and framing constants."""
    guard = f"{_c_ident(spec.metadata.name).upper()}_H"
    lines = [
        f"/* C Protocol Header for {spec.metadata.name} (v{spec.metadata.version}) */",
        "/* Auto-generated by OmniUART */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        f"#define {guard}_BAUDRATE {spec.serial_config.baudrate}",
        "",
        "/* Command Opcodes */",
        "typedef enum {",
    ]
    for cmd in spec.commands:
        cmd_id = cmd.id if isinstance(cmd.id, int) else 0
        lines.append(f"    CMD_{_c_ident(cmd.name).upper()} = {cmd_id},")
    lines.extend([
        "} command_id_t;",
        "",
    ])

    for cmd in spec.commands:
        struct_name = f"{_c_ident(cmd.name).lower()}_req_t"
        lines.append(f"typedef struct __attribute__((packed)) {{")
        lines.append("    uint8_t command_id;")
        if cmd.parameters:
            for p in cmd.parameters:
                lines.append(f"    {_c_type(p.type)} {_c_ident(p.name)};")
        lines.append(f"}} {struct_name};")
        lines.append("")

    lines.extend([f"#endif /* {guard} */", ""])
    return "\n".join(lines)


def generate_python_dataclasses(spec: ProtocolSpec) -> str:
    """Generate Python dataclass representations of protocol commands and responses."""
    lines = [
        f'"""Python dataclasses for {spec.metadata.name} (v{spec.metadata.version}).',
        "Auto-generated by OmniUART.",
        '"""',
        "",
        "from __future__ import annotations",
        "from dataclasses import dataclass, field",
        "from typing import Optional, List",
        "",
    ]

    for cmd in spec.commands:
        class_name = _c_ident(cmd.name).title().replace("_", "") + "Request"
        lines.append("@dataclass")
        lines.append(f"class {class_name}:")
        lines.append(f'    """Payload for command {cmd.name} (ID: {cmd.id})."""')
        lines.append(f"    command_id: int = {cmd.id}")
        if cmd.parameters:
            for p in cmd.parameters:
                lines.append(f"    {_c_ident(p.name)}: {_py_type(p.type)} = 0")
        else:
            lines.append("    pass")
        lines.append("")

        if cmd.response:
            resp_class = _c_ident(cmd.name).title().replace("_", "") + "Response"
            lines.append("@dataclass")
            lines.append(f"class {resp_class}:")
            lines.append(f'    """Response payload for command {cmd.name}."""')
            if cmd.response.fields:
                for rf in cmd.response.fields:
                    lines.append(f"    {_c_ident(rf.name)}: {_py_type(rf.type)} = 0")
            else:
                lines.append("    pass")
            lines.append("")

    return "\n".join(lines)


def generate_json_schema() -> str:
    """Emit official JSON Schema for OmniUART ProtocolSpec."""
    from omniuart.core.models import ProtocolSpec
    return json.dumps(ProtocolSpec.model_json_schema(), indent=2)
